version: 1.0.{build}
image: WMF 5
clone_folder: c:\testsql
services: mssql2014
build:
  verbosity: minimal

install:
  - cinst pester
build_script:
- ps: Update-ModuleManifest -ModuleVersion $ENV:APPVEYOR_BUILD_VERSION -Path c:\testsql\testSQL.psd1
- ps: c:\testsql\source\test\Set-AppveyorSQL.ps1

test_script:
  - ps: $res = Invoke-Pester -Path "c:\testsql" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path c:\testsql\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

