version: 1.0.{build}
image: WMF 5
clone_folder: c:\testsql
services: mssql2014

install:
  - cinst pester

environment:
  access_token:
    secure: l7GCMr9GpxCMXPM4YnIF6j9ba8N4/L4PrlWziF1s3LNgFtgViKy4Qk9SZM19e2wM

#build: off
test: off

build_script:
- ps: Update-ModuleManifest -ModuleVersion $ENV:APPVEYOR_BUILD_VERSION -Path c:\testsql\testSQL.psd1
- ps: c:\testsql\source\test\Set-AppveyorSQL.ps1

#test_script:
#  - ps: $res = Invoke-Pester -Path "c:\testsql" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
#  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path c:\testsql\TestsResults.xml))
#  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

deploy_script:
  - ps: Start-Sleep -s 5
  - git config --global credential.helper store
  - git config --global user.email "martin@pughspace.com"
  - git config --global user.name "martin9700"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git commit --message "%APPVEYOR_BUILD_VERSION% commit [skip ci]"
  - git push

on_finish:
  - ps: $blockRdp = $true;iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
